# Change these first
owner: dinushchathurya # Your GitHub organization or username, where this repository lives
repo: furry-fiesta # The name of this repository

sites:
  - name: Codingtricks
    url: https://codingtricks.io
    expectedStatusCodes:
      - 301
      - 200
    assignees:
      - dinushchathurya
   - name: Codingtricks
     url: https://packagist.org/packages/dinushchathurya/srilankan-divisional-secretariats
     expectedStatusCodes:
      - 301
      - 200
    assignees:
      - dinushchathurya

status-website:
  baseUrl: /furry-fiesta
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Codingtricks
  introTitle: "Uptime monitor for Codebird services"
  #introMessage: 
  navbar:
    - title: Status
      href: /
