owner: dinushchathurya 
repo: codingtricks-uptime 

sites:
  - name: Codingtricks
    url: https://codingtricks.io
    expectedStatusCodes:
      - 301
      - 200
    assignees:
      - dinushchathurya

status-website:
  baseUrl: /codingtricks-uptime
  logoUrl: https://avatars.githubusercontent.com/u/68215031?s=200&v=4
  name: Codingtricks
  introTitle: "Uptime monitor for Codebird services"
 
  navbar:
    - title: Status
      href: /
