owner: dinushchathurya 
repo: codingtricks-uptime 

sites:
  - name: codingtricks.io
    url: https://codingtricks.io
    expectedStatusCodes:
      - 301
      - 200
    assignees:
      - dinushchathurya

status-website:
  theme: dark
  baseUrl: /codingtricks-uptime
  logoUrl: https://avatars.githubusercontent.com/u/68215031?s=200&v=4
  name: codingtricks.io
  introTitle: "Uptime monitor for codingtricks.io"
 
  navbar:
    - title: Status
      href: /
    
    - title: Website
      href: https://codingtricks.io/

    - title: GitHub
      href: https://github.com/$OWNER

 
