# Change these first
owner: dinushchathurya # Your GitHub organization or username, where this repository lives
repo: furry-fiesta # The name of this repository

sites:
  - name: Codingtricks
    url: https://codingtricks.io
    expectedStatusCodes:
      - 301
      - 200
    assignees:
      - dinushchathurya

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
   baseUrl: https://github.com/dinushchathurya/furry-fiesta/
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Codingtricks
  introTitle: "Uptime monitor for Codebird services"
  #introMessage: 
  navbar:
    - title: Status
      href: /
